import logging
import os
import re
from pathlib import Path

from sqlalchemy.orm import Session

try:
    from backend.app.models.repository_file import RepositoryFile
    from backend.app.services.symbol_service import parse_repository_symbols
except ModuleNotFoundError:
    from app.models.repository_file import RepositoryFile
    from app.services.symbol_service import parse_repository_symbols

logger = logging.getLogger(__name__)

# Directories to ignore during scanning
IGNORED_DIRS = {
    ".git",
    "node_modules",
    "dist",
    "build",
    "target",
    "venv",
    ".venv",
    "__pycache__",
    "coverage",
    "vendor",
    ".pytest_cache",
    ".tox",
    ".idea",
    ".vscode",
}

# Known binary extensions
BINARY_EXTENSIONS = {
    # Images
    ".png",
    ".jpg",
    ".jpeg",
    ".gif",
    ".bmp",
    ".ico",
    ".webp",
    ".tiff",
    ".psd",
    ".raw",
    # Audio/Video
    ".mp3",
    ".wav",
    ".ogg",
    ".flac",
    ".mp4",
    ".avi",
    ".mkv",
    ".mov",
    ".webm",
    # Documents / Archives
    ".pdf",
    ".zip",
    ".tar",
    ".gz",
    ".tgz",
    ".bz2",
    ".xz",
    ".7z",
    ".rar",
    ".jar",
    ".war",
    # Executables / Libraries
    ".exe",
    ".dll",
    ".so",
    ".dylib",
    ".bin",
    ".iso",
    ".dmg",
    ".app",
    ".msi",
    # Bytecode / Objects
    ".pyc",
    ".pyo",
    ".pyd",
    ".class",
    ".o",
    ".a",
    ".obj",
    ".wasm",
    # Fonts
    ".ttf",
    ".otf",
    ".woff",
    ".woff2",
    ".eot",
    # Database files
    ".sqlite",
    ".db",
    ".sqlite3",
}

# Generated file patterns
GENERATED_EXTENSIONS = {
    ".pb.go",
    ".pb.gw.go",
    "_pb2.py",
    "_pb2_grpc.py",
    ".g.dart",
    ".generated.ts",
    ".generated.js",
    ".generated.go",
    ".auto.ts",
}

GENERATED_FILENAMES = {
    "package-lock.json",
    "yarn.lock",
    "pnpm-lock.yaml",
    "poetry.lock",
    "pipfile.lock",
    "composer.lock",
    "cargo.lock",
    "gemfile.lock",
    "flake.lock",
}

GENERATED_HEADER_MARKERS = [
    b"@generated",
    b"do not edit",
    b"code generated by",
    b"this file is generated",
    b"auto-generated",
    b"autogenerated",
]

# Language mappings
EXTENSION_TO_LANGUAGE = {
    ".py": "Python",
    ".pyi": "Python",
    ".js": "JavaScript",
    ".mjs": "JavaScript",
    ".cjs": "JavaScript",
    ".jsx": "JavaScript",
    ".ts": "TypeScript",
    ".mts": "TypeScript",
    ".cts": "TypeScript",
    ".tsx": "TypeScript",
    ".html": "HTML",
    ".htm": "HTML",
    ".css": "CSS",
    ".scss": "SCSS",
    ".sass": "SASS",
    ".less": "Less",
    ".json": "JSON",
    ".jsonc": "JSON",
    ".md": "Markdown",
    ".markdown": "Markdown",
    ".go": "Go",
    ".rs": "Rust",
    ".java": "Java",
    ".kt": "Kotlin",
    ".kts": "Kotlin",
    ".scala": "Scala",
    ".c": "C",
    ".h": "C",
    ".cpp": "C++",
    ".cc": "C++",
    ".cxx": "C++",
    ".hpp": "C++",
    ".hxx": "C++",
    ".cs": "C#",
    ".php": "PHP",
    ".rb": "Ruby",
    ".swift": "Swift",
    ".sh": "Shell",
    ".bash": "Shell",
    ".zsh": "Shell",
    ".bat": "Batch",
    ".cmd": "Batch",
    ".ps1": "PowerShell",
    ".sql": "SQL",
    ".yaml": "YAML",
    ".yml": "YAML",
    ".toml": "TOML",
    ".xml": "XML",
    ".graphql": "GraphQL",
    ".gql": "GraphQL",
    ".r": "R",
    ".dart": "Dart",
    ".lua": "Lua",
}

# Secret patterns
SECRET_FILENAME_PREFIXES = (".env",)
SECRET_EXTENSIONS = {
    ".pem",
    ".key",
    ".pkcs12",
    ".pfx",
    ".p12",
    ".kdbx",
}
SECRET_EXACT_NAMES = {
    "id_rsa",
    "id_dsa",
    "id_ecdsa",
    "id_ed25519",
    "credentials.json",
    "client_secret.json",
    "client_secrets.json",
    "token.json",
    ".npmrc",
    ".pypirc",
}
SECRET_NAME_PATTERNS = re.compile(
    r"(secret|credential|service[-_]?account|private[-_]?key)",
    re.IGNORECASE,
)


def is_secret_file(filename: str) -> bool:
    """
    Determine if a file is a secret, key, or credentials file that must not be indexed.
    """
    lower_name = filename.lower()

    # 1. Environment variable files (.env, .env.local, .env.prod, etc.)
    if any(
        lower_name == prefix or lower_name.startswith(prefix + ".")
        for prefix in SECRET_FILENAME_PREFIXES
    ):
        return True

    # 2. Known secret filenames & private keys
    if lower_name in SECRET_EXACT_NAMES:
        return True

    # 3. Secret extensions (.pem, .key, etc.)
    ext = os.path.splitext(lower_name)[1]
    if ext in SECRET_EXTENSIONS:
        return True

    # 4. Sensitive credentials files (e.g. gcp-credentials.json, service-account.yaml)
    if ext in (".json", ".yaml", ".yml", ".xml") and SECRET_NAME_PATTERNS.search(
        lower_name
    ):
        return True

    return False


def is_binary_file(filename: str, file_path: Path) -> bool:
    """
    Check if a file is binary using extension heuristics and null-byte inspection.
    """
    ext = os.path.splitext(filename)[1].lower()
    if ext in BINARY_EXTENSIONS:
        return True

    # Null-byte inspection of initial buffer
    try:
        with open(file_path, "rb") as f:
            chunk = f.read(4096)
            if b"\x00" in chunk:
                return True
    except OSError:
        pass

    return False


def is_generated_file(filename: str, file_path: Path, is_binary: bool = False) -> bool:
    """
    Detect minified files, lockfiles, generated code headers, and source maps.
    """
    lower_name = filename.lower()

    # Minified files and sourcemaps
    if lower_name.endswith(
        (".min.js", ".min.css", "-min.js", "-min.css", ".js.map", ".css.map", ".ts.map")
    ):
        return True

    # Dependency lockfiles
    if lower_name in GENERATED_FILENAMES:
        return True

    # Generated code extensions
    for gen_ext in GENERATED_EXTENSIONS:
        if lower_name.endswith(gen_ext):
            return True

    # Inspect file header for generated code markers (skip binary or large files)
    if not is_binary:
        try:
            stat_res = file_path.stat()
            if 0 < stat_res.st_size <= 256 * 1024:
                with open(file_path, "rb") as f:
                    header = f.read(2048).lower()
                    if any(marker in header for marker in GENERATED_HEADER_MARKERS):
                        return True
        except OSError:
            pass

    return False


def detect_language(filename: str, ext: str) -> str | None:
    """
    Detect programming or markup language from filename and extension.
    """
    lower_name = filename.lower()
    if (
        lower_name == "dockerfile"
        or lower_name.startswith("dockerfile.")
        or lower_name.endswith(".dockerfile")
    ):
        return "Dockerfile"
    if lower_name in ("makefile", "gnumakefile") or lower_name.endswith(".mk"):
        return "Makefile"

    return EXTENSION_TO_LANGUAGE.get(ext.lower())


def scan_repository_files(
    db: Session,
    repository_id: int,
    repo_dir: Path,
) -> list[RepositoryFile]:
    """
    Scan an ingested repository workspace recursively and generate a file inventory.

    Security & filter rules:
    - Prunes IGNORED_DIRS (.git, node_modules, dist, build, target, venv, .venv, etc.)
    - Drops secrets (.env*, private keys, credentials)
    - Detects binary vs text files
    - Identifies generated/minified files
    - Computes language mapping
    """
    if not repo_dir.exists():
        logger.warning("Repository directory does not exist for scanning: %s", repo_dir)
        return []

    created_records: list[RepositoryFile] = []

    for root, dirs, files in os.walk(repo_dir):
        # 1. Prune ignored directories in-place to prevent traversing them
        dirs[:] = [
            d
            for d in dirs
            if d.lower() not in IGNORED_DIRS and not d.startswith(".git")
        ]

        for filename in files:
            # 2. Skip secrets
            if is_secret_file(filename):
                logger.debug("Skipping secret file: %s", filename)
                continue

            file_path = Path(root) / filename
            try:
                stat_res = file_path.lstat()
            except OSError:
                continue

            # Calculate normalized POSIX relative path
            rel_path = file_path.relative_to(repo_dir).as_posix()
            ext = os.path.splitext(filename)[1].lower()

            # Analyze properties
            binary = is_binary_file(filename, file_path)
            generated = is_generated_file(filename, file_path, binary)
            language = detect_language(filename, ext)

            record = RepositoryFile(
                repository_id=repository_id,
                path=rel_path,
                filename=filename,
                extension=ext,
                language=language,
                size_bytes=stat_res.st_size,
                is_binary=binary,
                is_generated=generated,
            )
            created_records.append(record)

    # Atomically replace any existing file records for this repository
    db.query(RepositoryFile).filter(
        RepositoryFile.repository_id == repository_id
    ).delete()
    if created_records:
        db.add_all(created_records)
    db.commit()

    logger.info(
        "Scanned and indexed %d files for repository %d",
        len(created_records),
        repository_id,
    )

    # Automatically parse symbols for supported source files
    try:
        parse_repository_symbols(db, repository_id, repo_dir)
    except Exception as e:
        logger.warning(
            "Failed to parse symbols for repository %d: %s", repository_id, e
        )

    return created_records
